component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/cern/.*
- ./bin/cern/clhep/.*
- ./bin/cern/colt/.*
- ./bin/cern/colt/bitvector/.*
- ./bin/cern/colt/buffer/.*
- ./bin/cern/colt/function/.*
- ./bin/cern/colt/list/.*
- ./bin/cern/colt/list/adapter/.*
- ./bin/cern/colt/map/.*
- ./bin/cern/colt/matrix/.*
- ./bin/cern/colt/matrix/bench/.*
- ./bin/cern/colt/matrix/bench/doc-files/.*
- ./bin/cern/colt/matrix/doc-files/.*
- ./bin/cern/colt/matrix/doublealgo/.*
- ./bin/cern/colt/matrix/impl/.*
- ./bin/cern/colt/matrix/linalg/.*
- ./bin/cern/colt/matrix/objectalgo/.*
- ./bin/cern/jet/.*
- ./bin/cern/jet/math/.*
- ./bin/cern/jet/random/.*
- ./bin/cern/jet/random/engine/.*
- ./bin/cern/jet/random/sampling/.*
- ./bin/cern/jet/stat/.*
- ./bin/cern/jet/stat/quantile/.*
- ./bin/corejava/.*
- ./bin/hep/.*
- ./bin/hep/aida/.*
- ./bin/hep/aida/bin/.*
- ./bin/hep/aida/doc-files/.*
- ./bin/hep/aida/ref/.*
- ./bin/hep/aida/ref/doc-files/.*
- ./doc/.*
- ./doc/api/.*
- ./doc/api/cern/.*
- ./doc/api/cern/clhep/.*
- ./doc/api/cern/clhep/class-use/.*
- ./doc/api/cern/colt/.*
- ./doc/api/cern/colt/bitvector/.*
- ./doc/api/cern/colt/bitvector/class-use/.*
- ./doc/api/cern/colt/buffer/.*
- ./doc/api/cern/colt/buffer/class-use/.*
- ./doc/api/cern/colt/class-use/.*
- ./doc/api/cern/colt/function/.*
- ./doc/api/cern/colt/function/class-use/.*
- ./doc/api/cern/colt/list/.*
- ./doc/api/cern/colt/list/adapter/.*
- ./doc/api/cern/colt/list/adapter/class-use/.*
- ./doc/api/cern/colt/list/class-use/.*
- ./doc/api/cern/colt/map/.*
- ./doc/api/cern/colt/map/class-use/.*
- ./doc/api/cern/colt/matrix/.*
- ./doc/api/cern/colt/matrix/bench/.*
- ./doc/api/cern/colt/matrix/bench/class-use/.*
- ./doc/api/cern/colt/matrix/bench/doc-files/.*
- ./doc/api/cern/colt/matrix/class-use/.*
- ./doc/api/cern/colt/matrix/doc-files/.*
- ./doc/api/cern/colt/matrix/doublealgo/.*
- ./doc/api/cern/colt/matrix/doublealgo/class-use/.*
- ./doc/api/cern/colt/matrix/impl/.*
- ./doc/api/cern/colt/matrix/impl/class-use/.*
- ./doc/api/cern/colt/matrix/linalg/.*
- ./doc/api/cern/colt/matrix/linalg/class-use/.*
- ./doc/api/cern/colt/matrix/objectalgo/.*
- ./doc/api/cern/colt/matrix/objectalgo/class-use/.*
- ./doc/api/cern/jet/.*
- ./doc/api/cern/jet/math/.*
- ./doc/api/cern/jet/math/class-use/.*
- ./doc/api/cern/jet/random/.*
- ./doc/api/cern/jet/random/class-use/.*
- ./doc/api/cern/jet/random/engine/.*
- ./doc/api/cern/jet/random/engine/class-use/.*
- ./doc/api/cern/jet/random/sampling/.*
- ./doc/api/cern/jet/random/sampling/class-use/.*
- ./doc/api/cern/jet/stat/.*
- ./doc/api/cern/jet/stat/class-use/.*
- ./doc/api/cern/jet/stat/quantile/.*
- ./doc/api/cern/jet/stat/quantile/class-use/.*
- ./doc/api/corejava/.*
- ./doc/api/corejava/class-use/.*
- ./doc/api/hep/.*
- ./doc/api/hep/aida/.*
- ./doc/api/hep/aida/bin/.*
- ./doc/api/hep/aida/bin/class-use/.*
- ./doc/api/hep/aida/class-use/.*
- ./doc/api/hep/aida/doc-files/.*
- ./doc/api/hep/aida/ref/.*
- ./doc/api/hep/aida/ref/class-use/.*
- ./doc/api/hep/aida/ref/doc-files/.*
- ./doc/api/index-files/.*
- ./doc/images/.*
- ./doc/licenses/.*
- ./lib/.*
- ./xdocs/.*
- ./xdocs/images/.*
- ./xdocs/licenses/.*
